Getting badcommand should throw error 'Returned 0, stdout is non-empty, stderr is empty' failed msg on test script

diff --git a/assign1/matrix b/assign1/matrix
--- a/assign1/matrix
+++ b/assign1/matrix
@@ -9,6 +9,31 @@
 datafilepath="datafile$$"
 trap "rm -f $datafilepath" EXIT		# Remove data file after dims function executes 
 
+#if [ "$#" = "0" ]
+#then
+#	cat > "$datafilepath"		
+#elif [ "$#" = "1" ]
+#then
+#	datafilepath=$1
+#fi
+
+# Dims function: Prints the dimensions of the matrix
+# as the number of rows, followed by a space, then the number
+# of columns (e.g. For a 5x6 matrix stdout will show '5 6')
+dims() {	
+	rows=0
+	while read numberLine 
+	do
+		rows=$(( rows + 1 ))		# Update row count
+		cols=0				# Initialize columns 	
+		for each in $numberLine	# Iterate over each value per row
+		do
+			cols=$(( cols + 1 ))	# Update column count
+		done
+	done < $datafilepath			# Stdin from arg1 (or piping stdout file)
+	echo "$rows $cols"			# Display rows and cols
+}
+
 if [ "$#" = "1" ]
 then
 	cat > "$datafilepath"		
@@ -17,34 +42,26 @@ then
 	datafilepath=$2
 fi
 
-# Dims function: Prints the dimensions of the matrix
-# as the number of rows, followed by a space, then the number
-# of columns (e.g. For a 5x6 matrix stdout will show '5 6')
-dims() {	
-	rows=0
-	while read myLine
-	do
-		rows=$(( rows + 1 ))		# Update row count
-		cols=0			
-		
-		for i in $myLine		# Iterate over each value per row
-		do
-			cols=$(( cols + 1 ))	# Update column count
-		done
-
-	done < $datafilepath			# Stdin from arg1 (or piping stdout file)
-	echo "$rows $cols"			# Display rows and cols 
-}
-
 # If number of args is greater than 2 or the file doesn't exist
 # print error message to stderr, nothing to stdout and return 1
 # else print the number of rows and cols to stdout and return 0
-if [ $# -gt 2 ] || [ ! -f $datafilepath ]
+if [ $# -gt 2 ] || [ $# -lt 1 ]
 then
-	echo "$@" >&2
-	exit 1 
-else
-	dims $datafilepath
+	echo "Error: Improper argument count" 1>&2
+#	echo "Arg count: $#"
+	exit 1
+fi
+
+if [ ! -f $datafilepath ]
+then
+	echo "Error: File $datafilepath does not exist." 1>&2
+#	echo "Arg count: $#"
+	exit 1
+fi
+
+if [ $# -eq 1 ] || [ $# -eq 2 ]
+then
+	dims $datafilepath	
 	exit 0
 fi
 
